# Uncomment the next line to define a global platform for your project
platform :ios, '13.6'

target 'MacDonaldsMenu' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "SwiftLint"

  # Pods for MacDonaldsMenu

  target 'MacDonaldsMenuTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
